"""add_managed_developer_id_to_users

Revision ID: 1be823f85d49
Revises: f34a615a4285
Create Date: 2026-04-18 19:33:32.589873
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1be823f85d49'
down_revision: Union[str, None] = 'f34a615a4285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_score_history_bounty_id'), 'score_history', ['bounty_id'], unique=False)
    op.drop_constraint(op.f('uq_submissions_share_token'), 'submissions', type_='unique')
    op.drop_index(op.f('ix_submissions_share_token'), table_name='submissions')
    op.create_index(op.f('ix_submissions_share_token'), 'submissions', ['share_token'], unique=True)
    op.drop_index(op.f('ix_training_runs_public'), table_name='training_runs')
    op.create_index(op.f('ix_training_runs_agent_user_id'), 'training_runs', ['agent_user_id'], unique=False)
    op.add_column('users', sa.Column('managed_developer_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'managed_developer_id')
    op.drop_index(op.f('ix_training_runs_agent_user_id'), table_name='training_runs')
    op.create_index(op.f('ix_training_runs_public'), 'training_runs', ['public'], unique=False)
    op.drop_index(op.f('ix_submissions_share_token'), table_name='submissions')
    op.create_index(op.f('ix_submissions_share_token'), 'submissions', ['share_token'], unique=False)
    op.create_unique_constraint(op.f('uq_submissions_share_token'), 'submissions', ['share_token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_score_history_bounty_id'), table_name='score_history')
    # ### end Alembic commands ###
