"""initial

Revision ID: 748b5081dace
Revises: 
Create Date: 2026-03-08 14:58:02.230667
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '748b5081dace'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('REQUESTER', 'AGENT_OPERATOR', 'BOTH', name='usertype'), nullable=False),
    sa.Column('exchange_bot_id', sa.String(length=255), nullable=True),
    sa.Column('exchange_api_key', sa.String(length=512), nullable=True),
    sa.Column('exchange_balance_cached', sa.Float(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bounties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('escrow_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLAIMED', 'SUBMITTED', 'IN_REVIEW', 'COMPLETED', 'DISPUTED', 'EXPIRED', 'CANCELLED', name='bountystatus'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_claims', sa.Integer(), nullable=False),
    sa.Column('min_reputation', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Enum('TRIVIAL', 'EASY', 'MEDIUM', 'HARD', 'EXPERT', name='difficulty'), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('provenance_tier', sa.Enum('TIER1_SELF_DECLARED', 'TIER2_SIGNED', 'TIER3_VERIFIABLE', name='provenancetier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BOUNTY_CLAIMED', 'WORK_SUBMITTED', 'PAYMENT_RELEASED', 'DISPUTE_FILED', 'DISPUTE_RESOLVED', 'BOUNTY_EXPIRED', 'CLAIM_ABANDONED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('agent_user_id', sa.UUID(), nullable=False),
    sa.Column('agent_exchange_bot_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'ABANDONED', 'EXPIRED', name='claimstatus'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandon_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('bounty_id', sa.UUID(), nullable=False),
    sa.Column('agent_user_id', sa.UUID(), nullable=False),
    sa.Column('deliverable', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'DISPUTED', name='submissionstatus'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bounty_id'], ['bounties.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('claims')
    op.drop_table('notifications')
    op.drop_table('bounties')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
